#启用端口
server:
  port: 8089

spring:
  ##数据库配置
  datasource:
    url: jdbc:mysql://122.51.4.234:3306/longqiao_info?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: hzp123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  ##日期转字符串时格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis-plus配置
mybatis-plus:
  configuration:
    ## 数据库驼峰转换下划线（不转换）
    map-underscore-to-camel-case: false

  #打印sql语句及执行结果
  #mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

  ##打印sql
  ##格式：logging.level.Mapper类的包=debug
  #logging.level.com.village.dataAnlysis.domain.mapper=debug

  #log4j.logger.com.ibatis=DEBUG
  #log4j.logger.com.ibatis.common.jdbc.SimpleDataSource=DEBUG
  #log4j.logger.com.ibatis.common.jdbc.ScriptRunner=DEBUG
  #log4j.logger.com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate=DEBUG
  #log4j.logger.Java.sql.Connection=DEBUG
  #log4j.logger.java.sql.Statement=DEBUG
  #log4j.logger.java.sql.PreparedStatement=DEBUG



  #pagehelper分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#management.security.enabled=false
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *
#  endpoint:
#    health:
#      show-details: always
#      shutdown:
#        enabled: true



#spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
#spring.jackson.time-zone=GMT+8


## REDIS (RedisProperties)
## Redis数据库索引（默认为0）
#spring.redis.database=0
## Redis服务器地址
#spring.redis.host=122.51.4.234
## Redis服务器连接端口
#spring.redis.port=6379
## Redis服务器连接密码（默认为空）
#spring.redis.password=
## 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=8
## 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
## 连接池中的最大空闲连接
#spring.redis.pool.max-idle=8
## 连接池中的最小空闲连接
#spring.redis.pool.min-idle=0
## 连接超时时间（毫秒）
#spring.redis.timeout=500


